#!/usr/bin/env bash
# Disposable integration fixture; the runner provider remains the config owner.
set -euo pipefail
cd /workspace
test_tmp="$(mktemp -d)"
trap 'rm -rf "$test_tmp"' EXIT
export CRF_CFGDIR="$test_tmp/config" CRF_RUNDIR="$test_tmp/run" CRF_SOURCE_ONLY=1
mkdir -p "$CRF_CFGDIR" "$CRF_RUNDIR"
# shellcheck source=/dev/null
source src/usr/local/emhttp/plugins/ci-runner-farm/include/runner-farm.sh
# shellcheck disable=SC2034 # configuration consumed by sourced provider functions
{
  CACHE_ROOT=/mounted-cache; CACHE_MOUNTS="pnpm-store:$1"
  ACCESS_TOKEN=''; NO_REGISTER=1; GH_SCOPE=org; GH_OWNER=example
  DIND=false; SHARE_DOCKER_SOCK=false; NETWORK_ISOLATION=off
  WORK_TMPFS_SIZE=64m; RUNNER_LABELS=self-hosted
}
host() { printf 'mockhost\n'; }
runner_host_service_ipv4() { printf '192.0.2.10\n'; }
github_build_args 1 test-runner
expected_store="$1"; version="$2"; mode="$3"
pnpm_cmd=(node "/opt/pnpm$version/node_modules/pnpm/bin/pnpm.cjs")
mkdir -p /_work/project
mkdir -p "$HOME"
cd /_work/project
# Both disks are real mounts. This prevents a same-filesystem false positive.
[ "$(stat -c %d /_work)" != "$(stat -c %d "$expected_store")" ]
if [ "$mode" = seed ]; then
  unset PNPM_CONFIG_STORE_DIR npm_config_store_dir
  [ "$("${pnpm_cmd[@]}" store path --silent)" = "/_work/.pnpm-store/v$version" ]
fi
# Consume only environment values generated by the actual adapter.
for ((i=0; i<${#ARGS[@]}; i++)); do
  if [ "${ARGS[$i]}" = -e ]; then
    case "${ARGS[$((i+1))]}" in
      PNPM_CONFIG_STORE_DIR=*|npm_config_store_dir=*) export "${ARGS[$((i+1))]}" ;;
    esac
  fi
done
[ "$("${pnpm_cmd[@]}" store path --silent)" = "$expected_store/v$version" ]
printf '%s\n' '{"private":true,"dependencies":{"is-number":"7.0.0"}}' > package.json
install_args=(install --ignore-scripts --reporter=append-only)
if [ "$mode" != seed ]; then
  # CI checks out its lockfile. The fixture also retains resolver metadata
  # separately because pnpm 11 checks supply-chain policy during offline runs.
  cp "/mounted-cache/fixture-v$version.yaml" pnpm-lock.yaml
  install_args+=(--offline --frozen-lockfile)
fi
"${pnpm_cmd[@]}" "${install_args[@]}"
[ "$mode" != seed ] || cp pnpm-lock.yaml "/mounted-cache/fixture-v$version.yaml"
node -e 'if (!require("is-number")(42)) process.exit(1)'
[ ! -e /_work/.pnpm-store ]
find "$expected_store/v$version" -type f -print -quit | grep -q .
printf 'pnpm %s uid %s %s selected persistent %s; workspace store absent.\n' \
  "$version" "$(id -u)" "$mode" "$expected_store"
